# Generated by Django 4.2 on 2023-05-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='disliked_users',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='liked_users',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='liked_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='mark',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=10),
        ),
        migrations.DeleteModel(
            name='CommentDislike',
        ),
    ]
